name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      # Kör allt via solution-filen i repo-root
      - name: Restore
        run: dotnet restore "CI_CD_Group_8.sln"

      - name: Build
        run: dotnet build "CI_CD_Group_8.sln" -c Release --no-restore

      - name: Test
        run: dotnet test "CI_CD_Group_8.sln" -c Release --no-build --verbosity normal
